ProductCreator As screen:

    ContractInfoLabel_1 As label:
        Color: |
            =RGBA(0, 18, 107, 1)
        Height: =64
        Size: =20
        Text: ="Create a product"
        Width: =1230
        X: =30
        Y: =40
        ZIndex: =1

    Label7 As label:
        Height: =62
        Text: ="Name"
        Width: =342
        X: =30
        Y: =143
        ZIndex: =2

    Label7_1 As label:
        Height: =62
        Text: ="Department"
        Width: =342
        X: =30
        Y: =205
        ZIndex: =3

    TextInput1 As text:
        Default: =""
        HintText: ="Name"
        X: =372
        Y: =154
        ZIndex: =4

    TextInput1_1 As text:
        Default: =""
        HintText: ="Department"
        X: =372
        Y: =216
        ZIndex: =5

