ProductSpecification As screen:

    ProductSpecBackArrow As icon.BackArrow:
        Icon: =Icon.BackArrow
        OnSelect: =Back()
        X: =1260
        Y: =40
        ZIndex: =1

    ProductInfoLabel As label:
        Color: |
            =RGBA(0, 18, 107, 1)
        Height: =59
        Size: =20
        Text: ="Information about product with idea"
        Width: =465
        X: =30
        Y: =45
        ZIndex: =2

    PartyNamelabel_8 As label:
        Color: |
            =RGBA(0, 18, 107, 1)
        Height: =59
        Size: =20
        Text: |-
            ="Name:
            "
        Width: =405
        X: =75
        Y: =135
        ZIndex: =3

    PartyIdentifierLabel_5 As label:
        Color: |
            =RGBA(0, 18, 107, 1)
        Height: =59
        Size: =20
        Text: |-
            ="Department:"
        Width: =405
        X: =75
        Y: =213
        ZIndex: =4

