ProductCreator As screen:
    OnVisible: |-
        =Set(_productname, "");
        Set(_department, "");

    ContractInfoLabel_1 As label:
        Color: |
            =RGBA(0, 18, 107, 1)
        Height: =64
        Size: =20
        Text: ="Create a product"
        Width: =1230
        X: =30
        Y: =40
        ZIndex: =1

    CreateProductNameLabel As label:
        Height: =62
        Text: ="Name"
        Width: =342
        X: =30
        Y: =143
        ZIndex: =2

    CreateProductDepartmentLabel As label:
        Height: =62
        Text: ="Department"
        Width: =342
        X: =30
        Y: =205
        ZIndex: =3

    CreateProductNameField As text:
        Default: =""
        HintText: ="Name"
        X: =372
        Y: =154
        ZIndex: =4

    CreateProductDepartmentField As text:
        Default: =""
        HintText: ="Department"
        X: =372
        Y: =216
        ZIndex: =5

    Icon2 As icon.Send:
        Icon: =Icon.Send
        OnSelect: |-
            =Clear(ProductCollection);
            Collect(ProductCollection, PostProduct.Run(CreateProductNameField.Text, CreateProductDepartmentField.Text);
            Navigate(ProductSpecification, None, { 
                name: CreateProductNameField.Text,
                department: CreateProductDepartmentField.Text
            }));
        X: =1280
        Y: =687
        ZIndex: =6

    PartyBackArrow_2 As icon.BackArrow:
        Icon: =Icon.BackArrow
        OnSelect: =Back()
        X: =1280
        Y: =60
        ZIndex: =7

