ProductSpecification As screen:
    OnVisible: |-
        =Set(_productSpecName, name);
        Set(_productSpecDepartment, department);

    PartySpecBackArrow_1 As icon.BackArrow:
        Height: =60
        Icon: =Icon.BackArrow
        OnSelect: |-
            =Back();
            Set(_productSpecName, "");
            Set(_productSpecDepartment, "");
        PaddingBottom: =10
        PaddingTop: =10
        Width: =60
        X: =1260
        Y: =40
        ZIndex: =1

    PartyInfoLabel_1 As label:
        Color: |
            =RGBA(0, 18, 107, 1)
        Height: =64
        Size: =20
        Text: |-
            ="Created Product:"
        Width: =1230
        X: =30
        Y: =40
        ZIndex: =2

    PartyNamelabel_1 As label:
        Color: |
            =RGBA(0, 18, 107, 1)
        Height: =59
        Size: =20
        Text: |-
            ="Name: " & _productSpecName
        Width: =405
        X: =75
        Y: =104
        ZIndex: =3

    PartyIdentifierLabel_1 As label:
        Color: |
            =RGBA(0, 18, 107, 1)
        Height: =59
        Size: =20
        Text: |-
            ="Department: " & _productSpecDepartment
        Width: =405
        X: =75
        Y: =163
        ZIndex: =4

    PartyInfoLabel_2 As label:
        Color: |
            =RGBA(0, 18, 107, 1)
        Height: =64
        Size: =20
        Text: |-
            ="Related UUID: " & uuid.uuid
        Width: =1230
        X: =30
        Y: =222
        ZIndex: =5

    Icon3 As icon.Copy:
        Height: =60
        Icon: =Icon.Copy
        OnSelect: =Notify("Not supported", NotificationType.Error)
        PaddingBottom: =10
        PaddingTop: =10
        Width: =60
        X: =1260
        Y: =224
        ZIndex: =6

