ProductSpecification As screen:
    OnVisible: |-
        =Set(_productSpecName, name);
        Set(_productSpecDepartment, department);

    PartySpecBackArrow_1 As icon.BackArrow:
        Icon: =Icon.BackArrow
        OnSelect: =Back()
        X: =1260
        Y: =40
        ZIndex: =1

    PartyInfoLabel_1 As label:
        Color: |
            =RGBA(0, 18, 107, 1)
        Height: =64
        Size: =20
        Text: |-
            ="Created Product:"
        Width: =1230
        X: =30
        Y: =40
        ZIndex: =2

    PartyNamelabel_1 As label:
        Color: |
            =RGBA(0, 18, 107, 1)
        Height: =59
        Size: =20
        Text: |-
            ="Name: " & name
        Width: =405
        X: =75
        Y: =135
        ZIndex: =3

    PartyIdentifierLabel_1 As label:
        Color: |
            =RGBA(0, 18, 107, 1)
        Height: =59
        Size: =20
        Text: |-
            ="Department: " & department
        Width: =405
        X: =75
        Y: =213
        ZIndex: =4

